server:
  port: 8880

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: false
      service-discovery:
        timeout: 60000
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #      default-filters:
      #        - name: Hystrix
      #          args:
      #            name: fallbackcmd
      #            fallbackUri: forward:/fallback
      routes:

  .